---
language: perl
perl:
  - blead
  - blead-thr
  - dev
  - dev-thr
  - 5.24
  - 5.24-thr
  - 5.22
  - 5.22-thr
  - 5.20
  - 5.20-thr
  - 5.18
  - 5.18-thr
  - 5.16
  - 5.16-thr
  - 5.14
  - 5.14-thr
  - 5.12
  - 5.12-thr
  - 5.10
  - 5.10-thr
  - 5.8
  - 5.8-thr
sudo: false
matrix:
  allow_failures:
    - perl: blead
    - perl: blead-thr
  include:
    - env: COVERAGE=1
      perl: 5.24
env:
  global:
    - RELEASE_TESTING=1
    - AUTHOR_TESTING=1
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
