--- #YAML:1.0
name: Nagios-Object
version: 0.04
license: gpl
distribution_type: module
requires:
  perl: 5.6.0
recommends: {}
build_requires:
  Test::More: 0
conflicts: {}
provides:
  Nagios::Config:
    file: lib/Nagios/Config.pm
  Nagios::Config::File:
    file: lib/Nagios/Config/File.pm
  Nagios::Object:
    file: lib/Nagios/Object.pm
  Nagios::Object::Config:
    file: lib/Nagios/Object/Config.pm
  Nagios::StatusLog:
    file: lib/Nagios/StatusLog.pm
generated_by: Module::Build version 0.21
