---
name: Nagios-Object
version: 0.21.7
author:
  - 'Duncan Ferguson <duncs@cpan.org>'
abstract: 'Nagios::Object - Nagios object configuration parsing.'
license: gpl
resources:
  license: http://www.gnu.org/licenses/old-licenses/gpl-1.0.txt
requires:
  perl: 5.6.1
build_requires:
  Data::Dumper: 0.01
  Module::Build: 0.26
  Scalar::Util: 0.01
  Test::Exception: 0.01
  Test::More: 0.01
  Test::NoWarnings: 0.08
provides:
  Nagios::Config:
    file: lib/Nagios/Config.pm
    version: 35
  Nagios::Config::File:
    file: lib/Nagios/Config/File.pm
    version: 35
  Nagios::Host:
    file: lib/Nagios/Host.pm
    version: 0.21
  Nagios::Host::Status:
    file: lib/Nagios/StatusLog.pm
    version: 0.1
  Nagios::HostGroup:
    file: lib/Nagios/Object.pm
    version: 0
  Nagios::Info::Status:
    file: lib/Nagios/StatusLog.pm
    version: 0.1
  Nagios::Object:
    file: lib/Nagios/Object.pm
    version: 39
  Nagios::Object::Config:
    file: lib/Nagios/Object/Config.pm
    version: 36
  Nagios::Program::Status:
    file: lib/Nagios/StatusLog.pm
    version: 0.1
  Nagios::Service:
    file: lib/Nagios/Service.pm
    version: 0.21
  Nagios::Service::Status:
    file: lib/Nagios/StatusLog.pm
    version: 0.1
  Nagios::ServiceGroup:
    file: lib/Nagios/Object.pm
    version: 0
  Nagios::StatusLog:
    file: lib/Nagios/StatusLog.pm
    version: 39
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
