---
name: Nagios-Object
version: 0.21.1
author:
  - 'Duncan Ferguson <duncs@cpan.org>'
abstract: Nagios::Object - Nagios object configuration parsing.
license: gpl
requires:
  perl: 5.6.1
build_requires:
  Data::Dumper: 0.01
  Module::Build: 0.26
  Scalar::Util: 0.01
  Test::Exception: 0.01
  Test::More: 0.01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  Nagios::Config:
    file: lib/Nagios/Config.pm
    version: 35
  Nagios::Config::File:
    file: lib/Nagios/Config/File.pm
    version: 35
  Nagios::Host:
    file: lib/Nagios/Object.pm
    version: 0
  Nagios::Host::Status:
    file: lib/Nagios/StatusLog.pm
    version: 000000
  Nagios::HostGroup:
    file: lib/Nagios/Object.pm
    version: 0
  Nagios::Info::Status:
    file: lib/Nagios/StatusLog.pm
    version: 000000
  Nagios::Object:
    file: lib/Nagios/Object.pm
    version: 35
  Nagios::Object::Config:
    file: lib/Nagios/Object/Config.pm
    version: 35
  Nagios::Program::Status:
    file: lib/Nagios/StatusLog.pm
    version: 000000
  Nagios::Service:
    file: lib/Nagios/Object.pm
    version: 0
  Nagios::Service::Status:
    file: lib/Nagios/StatusLog.pm
    version: 000000
  Nagios::ServiceGroup:
    file: lib/Nagios/Object.pm
    version: 0
  Nagios::StatusLog:
    file: lib/Nagios/StatusLog.pm
    version: 35
resources:
  license: http://www.opensource.org/licenses/gpl-license.php
