---
name: Nagios-Object
version: 0.08
author: ~
abstract: ~
license: gpl
requires:
  perl: 5.6.0
build_requires:
  Test::More: 0
provides:
  Nagios::Config:
    file: lib/Nagios/Config.pm
  Nagios::Config::File:
    file: lib/Nagios/Config/File.pm
  Nagios::Host::Status:
    file: lib/Nagios/StatusLog.pm
  Nagios::Object:
    file: lib/Nagios/Object.pm
    version: 0.06
  Nagios::Object::Config:
    file: lib/Nagios/Object/Config.pm
  Nagios::Program::Status:
    file: lib/Nagios/StatusLog.pm
  Nagios::Service::Status:
    file: lib/Nagios/StatusLog.pm
  Nagios::StatusLog:
    file: lib/Nagios/StatusLog.pm
generated_by: Module::Build version 0.26
